package network

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	"github.com/ecadlabs/gotez/v2/clientv2/internal/transport"
)

// Code generated by generate.go DO NOT EDIT.


var path_Connections = template.Must(template.New("path").Parse("/network/connections"))

func Connections(ctx context.Context, cl *client.Client) (*ConnectionsResponse, error) {
	var path strings.Builder
	if err := path_Connections.Execute(&path, nil); err != nil {
		return nil, err
	}
	response := new(ConnectionsResponse)
	if err := (*transport.Transport)(cl).Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}

