//go:build ignore

package main

import (
	"log"
	"os"
	"text/template"
)

const (
	ModeVar int = iota
	ModeConstruct
	ModeConstructPtr
	ModeAllocate
)

type queryParam struct {
	Field string
	Param string
}

type typeDef struct {
	Func         string
	RequestType  string
	Path         string
	QueryParams  map[string]string
	Method       string
	ResponseType string
	Mode         int
}

var types = []*typeDef{
	{
		RequestType:  "SimpleRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/hash",
		Func:         "BlockHash",
		ResponseType: "BlockHash",
		Mode:         ModeAllocate,
	},
	{
		RequestType:  "SimpleRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/protocols",
		Func:         "BlockProtocols",
		ResponseType: "BlockProtocols",
		Mode:         ModeAllocate,
	},
	{
		RequestType:  "SimpleRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/header/shell",
		Func:         "BlockShellHeader",
		ResponseType: "BlockShellHeader",
		Mode:         ModeAllocate,
	},
	{
		RequestType:  "BlockRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/header",
		QueryParams:  map[string]string{"metadata": "Metadata"},
		Func:         "BlockHeader",
		ResponseType: "BlockHeaderInfo",
		Mode:         ModeConstruct,
	},
	{
		RequestType:  "BlockRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}",
		QueryParams:  map[string]string{"metadata": "Metadata"},
		Func:         "Block",
		ResponseType: "BlockInfo",
		Mode:         ModeConstruct,
	},
	{
		RequestType:  "ContractRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/balance",
		Func:         "ContractBalance",
		ResponseType: "BigUint",
		Mode:         ModeVar,
	},
	{
		RequestType:  "ContractRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/balance_and_frozen_bonds",
		Func:         "ContractBalanceAndFrozenBonds",
		ResponseType: "BigUint",
		Mode:         ModeVar,
	},
	{
		RequestType:  "ContractRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/counter",
		Func:         "ContractCounter",
		ResponseType: "BigUint",
		Mode:         ModeVar,
	},
	{
		RequestType:  "RunOperationRequest",
		Method:       "POST",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/helpers/scripts/run_operation",
		Func:         "RunOperation",
		ResponseType: "OperationWithOptionalMetadata",
		Mode:         ModeAllocate,
	},
	{
		RequestType:  "ContextRequest",
		Method:       "GET",
		Path:         "/chains/{{.Chain}}/blocks/{{.Block}}/context/constants",
		Func:         "Constants",
		ResponseType: "Constants",
		Mode:         ModeConstruct,
	},
	{
		RequestType:  "InjectOperationRequest",
		Method:       "POST",
		Path:         "/injection/operation",
		QueryParams:  map[string]string{"chain": "Chain", "async": "Async"},
		Func:         "InjectOperation",
		ResponseType: "OperationHash",
		Mode:         ModeAllocate,
	},
}

const tplSrc = `package client

import (
	"context"
	"strings"
	"text/template"
)

// Code generated by generate.go DO NOT EDIT.
{{range .}}
var path_{{.Func}} = template.Must(template.New("path").Parse("{{.Path}}"))

func (client *Client) {{.Func}}(ctx context.Context, r *{{.RequestType}}) ({{if eq .Mode 2 3}}*{{end}}{{.ResponseType}}, error) {
	var path strings.Builder
	if err := path_{{.Func}}.Execute(&path, r); err != nil {
		return nil, err
	}
	{{with .QueryParams -}}
	params := map[string]any{
		{{- range $p, $f := .}}
		"{{$p}}": r.{{$f}},{{end}}
	}
	{{end -}}
	{{if eq .Method "POST" -}}
	payload := r.Payload
	{{end -}}
	{{if eq .Mode 0 -}}
	var response {{.ResponseType}}
	{{else if eq .Mode 1 2 -}}
	response, err := new{{.ResponseType}}(r.Protocol)
	if err != nil {
		return nil, err
	}
	{{else -}}
	response := new({{.ResponseType}})
	{{end -}}
	if err := client.request(ctx, "{{.Method}}", path.String(), {{if .QueryParams}}params{{else}}nil{{end}}, {{if eq .Method "POST" -}}payload{{else}}nil{{end}}, {{if eq .Mode 0}}&{{end}}response); err != nil {
		return nil, err
	}
	return response, nil
}
{{end}}
`

var tpl = template.Must(template.New("formatter").Parse(tplSrc))

const outName = "request_gen.go"

func main() {
	fd, err := os.Create(outName)
	if err != nil {
		log.Fatal(err)
	}
	defer fd.Close()
	if err = tpl.Execute(fd, types); err != nil {
		log.Fatal(err)
	}
}
