package client

import (
	"context"
	"fmt"
	"github.com/ecadlabs/gotez/protocol"
)

// Code generated by generate.go DO NOT EDIT.

func (client *Client) BlockHeader(r *BlockRequest, ctx context.Context) (*protocol.BlockHeader, error) {
	tmp := *r
	if tmp.Chain == "" {
		tmp.Chain = client.Chain
	}
	req := fmt.Sprintf("/chains/%v/blocks/%v", tmp.Chain, tmp.Block)
	var response protocol.BlockHeader
	if err := client.request(req, "GET", &response, ctx); err != nil {
		return nil, err
	}
	return &response, nil
}

