package utils

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	"github.com/ecadlabs/gotez/v2"
)

// Code generated by generate.go DO NOT EDIT.


var path_InjectOperation = template.Must(template.New("path").Parse("/injection/operation"))

func InjectOperation(ctx context.Context, cl *client.Client, r *InjectOperationRequest) (*gotez.OperationHash, error) {
	var path strings.Builder
	if err := path_InjectOperation.Execute(&path, r); err != nil {
		return nil, err
	}
	params := map[string]any{
		"async": r.Async,
		"chain": r.Chain,
	}
	payload := r.Payload
	response := new(gotez.OperationHash)
	if err := cl.Request(ctx, "POST", path.String(), params, payload, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_IsBootstrapped = template.Must(template.New("path").Parse("/chains/{{.}}/is_bootstrapped"))

func IsBootstrapped(ctx context.Context, cl *client.Client, r *gotez.ChainID) (*BootstrappedResponse, error) {
	var path strings.Builder
	if err := path_IsBootstrapped.Execute(&path, r); err != nil {
		return nil, err
	}
	response := new(BootstrappedResponse)
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}

