package proto_014_PtKathma

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *RevealSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type RevealSuccessfulManagerResult_no_json_marshaller RevealSuccessfulManagerResult

	type json_RevealSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		RevealSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_RevealSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		RevealSuccessfulManagerResult_no_json_marshaller: RevealSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DelegationSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type DelegationSuccessfulManagerResult_no_json_marshaller DelegationSuccessfulManagerResult

	type json_DelegationSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		DelegationSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_DelegationSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		DelegationSuccessfulManagerResult_no_json_marshaller: DelegationSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DelegationInternalOperationResult) MarshalJSON() ([]byte, error) {
	type DelegationInternalOperationResult_no_json_marshaller DelegationInternalOperationResult

	type json_DelegationInternalOperationResult struct {
		Marker0 any `json:"kind"`
		DelegationInternalOperationResult_no_json_marshaller
	}

	tmp := json_DelegationInternalOperationResult {
		Marker0: self.OperationKind(),
		DelegationInternalOperationResult_no_json_marshaller: DelegationInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SetDepositsLimitSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type SetDepositsLimitSuccessfulManagerResult_no_json_marshaller SetDepositsLimitSuccessfulManagerResult

	type json_SetDepositsLimitSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		SetDepositsLimitSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_SetDepositsLimitSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		SetDepositsLimitSuccessfulManagerResult_no_json_marshaller: SetDepositsLimitSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorage) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorage_no_json_marshaller IncreasePaidStorage

	type json_IncreasePaidStorage struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorage_no_json_marshaller
	}

	tmp := json_IncreasePaidStorage {
		Marker0: self.OperationKind(),
		IncreasePaidStorage_no_json_marshaller: IncreasePaidStorage_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorageSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller IncreasePaidStorageSuccessfulManagerResult

	type json_IncreasePaidStorageSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_IncreasePaidStorageSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller: IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorageContentsAndResult) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorageContentsAndResult_no_json_marshaller IncreasePaidStorageContentsAndResult

	type json_IncreasePaidStorageContentsAndResult struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorageContentsAndResult_no_json_marshaller
	}

	tmp := json_IncreasePaidStorageContentsAndResult {
		Marker0: self.OperationKind(),
		IncreasePaidStorageContentsAndResult_no_json_marshaller: IncreasePaidStorageContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *VDFRevelation) MarshalJSON() ([]byte, error) {
	type VDFRevelation_no_json_marshaller VDFRevelation

	type json_VDFRevelation struct {
		Marker0 any `json:"kind"`
		VDFRevelation_no_json_marshaller
	}

	tmp := json_VDFRevelation {
		Marker0: self.OperationKind(),
		VDFRevelation_no_json_marshaller: VDFRevelation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALSlotAvailability) MarshalJSON() ([]byte, error) {
	type DALSlotAvailability_no_json_marshaller DALSlotAvailability

	type json_DALSlotAvailability struct {
		Marker0 any `json:"kind"`
		DALSlotAvailability_no_json_marshaller
	}

	tmp := json_DALSlotAvailability {
		Marker0: self.OperationKind(),
		DALSlotAvailability_no_json_marshaller: DALSlotAvailability_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALSlotAvailabilityContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALSlotAvailabilityContentsAndResult_no_json_marshaller DALSlotAvailabilityContentsAndResult

	type json_DALSlotAvailabilityContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALSlotAvailabilityContentsAndResult_no_json_marshaller
	}

	tmp := json_DALSlotAvailabilityContentsAndResult {
		Marker0: self.OperationKind(),
		DALSlotAvailabilityContentsAndResult_no_json_marshaller: DALSlotAvailabilityContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishSlotHeader) MarshalJSON() ([]byte, error) {
	type DALPublishSlotHeader_no_json_marshaller DALPublishSlotHeader

	type json_DALPublishSlotHeader struct {
		Marker0 any `json:"kind"`
		DALPublishSlotHeader_no_json_marshaller
	}

	tmp := json_DALPublishSlotHeader {
		Marker0: self.OperationKind(),
		DALPublishSlotHeader_no_json_marshaller: DALPublishSlotHeader_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SeedNonceRevelationContentsAndResult) MarshalJSON() ([]byte, error) {
	type SeedNonceRevelationContentsAndResult_no_json_marshaller SeedNonceRevelationContentsAndResult

	type json_SeedNonceRevelationContentsAndResult struct {
		Marker0 any `json:"kind"`
		SeedNonceRevelationContentsAndResult_no_json_marshaller
	}

	tmp := json_SeedNonceRevelationContentsAndResult {
		Marker0: self.OperationKind(),
		SeedNonceRevelationContentsAndResult_no_json_marshaller: SeedNonceRevelationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleEndorsementEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller DoubleEndorsementEvidenceContentsAndResult

	type json_DoubleEndorsementEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleEndorsementEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller: DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleBakingEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleBakingEvidenceContentsAndResult_no_json_marshaller DoubleBakingEvidenceContentsAndResult

	type json_DoubleBakingEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleBakingEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller: DoubleBakingEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ActivateAccountContentsAndResult) MarshalJSON() ([]byte, error) {
	type ActivateAccountContentsAndResult_no_json_marshaller ActivateAccountContentsAndResult

	type json_ActivateAccountContentsAndResult struct {
		Marker0 any `json:"kind"`
		ActivateAccountContentsAndResult_no_json_marshaller
	}

	tmp := json_ActivateAccountContentsAndResult {
		Marker0: self.OperationKind(),
		ActivateAccountContentsAndResult_no_json_marshaller: ActivateAccountContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoublePreendorsementEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller DoublePreendorsementEvidenceContentsAndResult

	type json_DoublePreendorsementEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoublePreendorsementEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller: DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *VDFRevelationContentsAndResult) MarshalJSON() ([]byte, error) {
	type VDFRevelationContentsAndResult_no_json_marshaller VDFRevelationContentsAndResult

	type json_VDFRevelationContentsAndResult struct {
		Marker0 any `json:"kind"`
		VDFRevelationContentsAndResult_no_json_marshaller
	}

	tmp := json_VDFRevelationContentsAndResult {
		Marker0: self.OperationKind(),
		VDFRevelationContentsAndResult_no_json_marshaller: VDFRevelationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *EndorsementContentsAndResult) MarshalJSON() ([]byte, error) {
	type EndorsementContentsAndResult_no_json_marshaller EndorsementContentsAndResult

	type json_EndorsementContentsAndResult struct {
		Marker0 any `json:"kind"`
		EndorsementContentsAndResult_no_json_marshaller
	}

	tmp := json_EndorsementContentsAndResult {
		Marker0: self.OperationKind(),
		EndorsementContentsAndResult_no_json_marshaller: EndorsementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreendorsementContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreendorsementContentsAndResult_no_json_marshaller PreendorsementContentsAndResult

	type json_PreendorsementContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreendorsementContentsAndResult_no_json_marshaller
	}

	tmp := json_PreendorsementContentsAndResult {
		Marker0: self.OperationKind(),
		PreendorsementContentsAndResult_no_json_marshaller: PreendorsementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RevealContentsAndResult) MarshalJSON() ([]byte, error) {
	type RevealContentsAndResult_no_json_marshaller RevealContentsAndResult

	type json_RevealContentsAndResult struct {
		Marker0 any `json:"kind"`
		RevealContentsAndResult_no_json_marshaller
	}

	tmp := json_RevealContentsAndResult {
		Marker0: self.OperationKind(),
		RevealContentsAndResult_no_json_marshaller: RevealContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DelegationContentsAndResult) MarshalJSON() ([]byte, error) {
	type DelegationContentsAndResult_no_json_marshaller DelegationContentsAndResult

	type json_DelegationContentsAndResult struct {
		Marker0 any `json:"kind"`
		DelegationContentsAndResult_no_json_marshaller
	}

	tmp := json_DelegationContentsAndResult {
		Marker0: self.OperationKind(),
		DelegationContentsAndResult_no_json_marshaller: DelegationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RegisterGlobalConstantContentsAndResult) MarshalJSON() ([]byte, error) {
	type RegisterGlobalConstantContentsAndResult_no_json_marshaller RegisterGlobalConstantContentsAndResult

	type json_RegisterGlobalConstantContentsAndResult struct {
		Marker0 any `json:"kind"`
		RegisterGlobalConstantContentsAndResult_no_json_marshaller
	}

	tmp := json_RegisterGlobalConstantContentsAndResult {
		Marker0: self.OperationKind(),
		RegisterGlobalConstantContentsAndResult_no_json_marshaller: RegisterGlobalConstantContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SetDepositsLimitContentsAndResult) MarshalJSON() ([]byte, error) {
	type SetDepositsLimitContentsAndResult_no_json_marshaller SetDepositsLimitContentsAndResult

	type json_SetDepositsLimitContentsAndResult struct {
		Marker0 any `json:"kind"`
		SetDepositsLimitContentsAndResult_no_json_marshaller
	}

	tmp := json_SetDepositsLimitContentsAndResult {
		Marker0: self.OperationKind(),
		SetDepositsLimitContentsAndResult_no_json_marshaller: SetDepositsLimitContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishSlotHeaderContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALPublishSlotHeaderContentsAndResult_no_json_marshaller DALPublishSlotHeaderContentsAndResult

	type json_DALPublishSlotHeaderContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller
	}

	tmp := json_DALPublishSlotHeaderContentsAndResult {
		Marker0: self.OperationKind(),
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller: DALPublishSlotHeaderContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransferTicketContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransferTicketContentsAndResult_no_json_marshaller TransferTicketContentsAndResult

	type json_TransferTicketContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransferTicketContentsAndResult_no_json_marshaller
	}

	tmp := json_TransferTicketContentsAndResult {
		Marker0: self.OperationKind(),
		TransferTicketContentsAndResult_no_json_marshaller: TransferTicketContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *EventInternalOperationResult) MarshalJSON() ([]byte, error) {
	type EventInternalOperationResult_no_json_marshaller EventInternalOperationResult

	type json_EventInternalOperationResult struct {
		Marker0 any `json:"kind"`
		EventInternalOperationResult_no_json_marshaller
	}

	tmp := json_EventInternalOperationResult {
		Marker0: self.OperationKind(),
		EventInternalOperationResult_no_json_marshaller: EventInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type TransactionSuccessfulManagerResult_no_json_marshaller TransactionSuccessfulManagerResult

	type json_TransactionSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		TransactionSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_TransactionSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		TransactionSuccessfulManagerResult_no_json_marshaller: TransactionSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransactionContentsAndResult_no_json_marshaller TransactionContentsAndResult

	type json_TransactionContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransactionContentsAndResult_no_json_marshaller
	}

	tmp := json_TransactionContentsAndResult {
		Marker0: self.OperationKind(),
		TransactionContentsAndResult_no_json_marshaller: TransactionContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionInternalOperationResult) MarshalJSON() ([]byte, error) {
	type TransactionInternalOperationResult_no_json_marshaller TransactionInternalOperationResult

	type json_TransactionInternalOperationResult struct {
		Marker0 any `json:"kind"`
		TransactionInternalOperationResult_no_json_marshaller
	}

	tmp := json_TransactionInternalOperationResult {
		Marker0: self.OperationKind(),
		TransactionInternalOperationResult_no_json_marshaller: TransactionInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BalanceUpdateFrozenBonds) MarshalJSON() ([]byte, error) {
	type BalanceUpdateFrozenBonds_no_json_marshaller BalanceUpdateFrozenBonds

	type json_BalanceUpdateFrozenBonds struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		BalanceUpdateFrozenBonds_no_json_marshaller
	}

	tmp := json_BalanceUpdateFrozenBonds {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateFrozenBonds_no_json_marshaller: BalanceUpdateFrozenBonds_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BalanceUpdateScRollupRefutationPunishments) MarshalJSON() ([]byte, error) {
	type BalanceUpdateScRollupRefutationPunishments_no_json_marshaller BalanceUpdateScRollupRefutationPunishments

	type json_BalanceUpdateScRollupRefutationPunishments struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		BalanceUpdateScRollupRefutationPunishments_no_json_marshaller
	}

	tmp := json_BalanceUpdateScRollupRefutationPunishments {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateScRollupRefutationPunishments_no_json_marshaller: BalanceUpdateScRollupRefutationPunishments_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type OriginationSuccessfulManagerResult_no_json_marshaller OriginationSuccessfulManagerResult

	type json_OriginationSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		OriginationSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_OriginationSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		OriginationSuccessfulManagerResult_no_json_marshaller: OriginationSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationContentsAndResult) MarshalJSON() ([]byte, error) {
	type OriginationContentsAndResult_no_json_marshaller OriginationContentsAndResult

	type json_OriginationContentsAndResult struct {
		Marker0 any `json:"kind"`
		OriginationContentsAndResult_no_json_marshaller
	}

	tmp := json_OriginationContentsAndResult {
		Marker0: self.OperationKind(),
		OriginationContentsAndResult_no_json_marshaller: OriginationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationInternalOperationResult) MarshalJSON() ([]byte, error) {
	type OriginationInternalOperationResult_no_json_marshaller OriginationInternalOperationResult

	type json_OriginationInternalOperationResult struct {
		Marker0 any `json:"kind"`
		OriginationInternalOperationResult_no_json_marshaller
	}

	tmp := json_OriginationInternalOperationResult {
		Marker0: self.OperationKind(),
		OriginationInternalOperationResult_no_json_marshaller: OriginationInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

