package mempool

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	"github.com/ecadlabs/gotez/v2/clientv2/internal/transport"
	"github.com/ecadlabs/gotez/v2"
)

// Code generated by generate.go DO NOT EDIT.


var path_PendingOperations = template.Must(template.New("path").Parse("/chains/{{.}}/mempool/pending_operations"))

func PendingOperations(ctx context.Context, cl *client.Client, r *gotez.ChainID) (*PendingOperationsResponse, error) {
	var path strings.Builder
	if err := path_PendingOperations.Execute(&path, r); err != nil {
		return nil, err
	}
	response := new(PendingOperationsResponse)
	if err := (*transport.Transport)(cl).Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_Monitor = template.Must(template.New("path").Parse("/chains/{{.}}/mempool/monitor_operations"))

func Monitor(ctx context.Context, cl *client.Client, r *gotez.ChainID) (<-chan *MonitorResponse, <-chan error, error) {
	var path strings.Builder
	if err := path_Monitor.Execute(&path, r); err != nil {
		return nil, nil, err
	}
	return transport.Stream[MonitorResponse](ctx, (*transport.Transport)(cl), path.String(), nil)
}

