package proto_016_PtMumbai

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *BalanceUpdateFrozenBonds) MarshalJSON() ([]byte, error) {
	type BalanceUpdateFrozenBonds_no_json_marshaller BalanceUpdateFrozenBonds

	type json_BalanceUpdateFrozenBonds struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		BalanceUpdateFrozenBonds_no_json_marshaller
	}

	tmp := json_BalanceUpdateFrozenBonds {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateFrozenBonds_no_json_marshaller: BalanceUpdateFrozenBonds_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BalanceUpdateSmartRollupRefutationPunishments) MarshalJSON() ([]byte, error) {
	type BalanceUpdateSmartRollupRefutationPunishments_no_json_marshaller BalanceUpdateSmartRollupRefutationPunishments

	type json_BalanceUpdateSmartRollupRefutationPunishments struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		BalanceUpdateSmartRollupRefutationPunishments_no_json_marshaller
	}

	tmp := json_BalanceUpdateSmartRollupRefutationPunishments {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateSmartRollupRefutationPunishments_no_json_marshaller: BalanceUpdateSmartRollupRefutationPunishments_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BalanceUpdateSmartRollupRefutationRewards) MarshalJSON() ([]byte, error) {
	type BalanceUpdateSmartRollupRefutationRewards_no_json_marshaller BalanceUpdateSmartRollupRefutationRewards

	type json_BalanceUpdateSmartRollupRefutationRewards struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		BalanceUpdateSmartRollupRefutationRewards_no_json_marshaller
	}

	tmp := json_BalanceUpdateSmartRollupRefutationRewards {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateSmartRollupRefutationRewards_no_json_marshaller: BalanceUpdateSmartRollupRefutationRewards_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type OriginationSuccessfulManagerResult_no_json_marshaller OriginationSuccessfulManagerResult

	type json_OriginationSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		OriginationSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_OriginationSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		OriginationSuccessfulManagerResult_no_json_marshaller: OriginationSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationContentsAndResult) MarshalJSON() ([]byte, error) {
	type OriginationContentsAndResult_no_json_marshaller OriginationContentsAndResult

	type json_OriginationContentsAndResult struct {
		Marker0 any `json:"kind"`
		OriginationContentsAndResult_no_json_marshaller
	}

	tmp := json_OriginationContentsAndResult {
		Marker0: self.OperationKind(),
		OriginationContentsAndResult_no_json_marshaller: OriginationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationInternalOperationResult) MarshalJSON() ([]byte, error) {
	type OriginationInternalOperationResult_no_json_marshaller OriginationInternalOperationResult

	type json_OriginationInternalOperationResult struct {
		Marker0 any `json:"kind"`
		OriginationInternalOperationResult_no_json_marshaller
	}

	tmp := json_OriginationInternalOperationResult {
		Marker0: self.OperationKind(),
		OriginationInternalOperationResult_no_json_marshaller: OriginationInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupOriginate) MarshalJSON() ([]byte, error) {
	type SmartRollupOriginate_no_json_marshaller SmartRollupOriginate

	type json_SmartRollupOriginate struct {
		Marker0 any `json:"kind"`
		SmartRollupOriginate_no_json_marshaller
	}

	tmp := json_SmartRollupOriginate {
		Marker0: self.OperationKind(),
		SmartRollupOriginate_no_json_marshaller: SmartRollupOriginate_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupOriginateSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type SmartRollupOriginateSuccessfulManagerResult_no_json_marshaller SmartRollupOriginateSuccessfulManagerResult

	type json_SmartRollupOriginateSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		SmartRollupOriginateSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_SmartRollupOriginateSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		SmartRollupOriginateSuccessfulManagerResult_no_json_marshaller: SmartRollupOriginateSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupOriginateContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupOriginateContentsAndResult_no_json_marshaller SmartRollupOriginateContentsAndResult

	type json_SmartRollupOriginateContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupOriginateContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupOriginateContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupOriginateContentsAndResult_no_json_marshaller: SmartRollupOriginateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupAddMessages) MarshalJSON() ([]byte, error) {
	type SmartRollupAddMessages_no_json_marshaller SmartRollupAddMessages

	type json_SmartRollupAddMessages struct {
		Marker0 any `json:"kind"`
		SmartRollupAddMessages_no_json_marshaller
	}

	tmp := json_SmartRollupAddMessages {
		Marker0: self.OperationKind(),
		SmartRollupAddMessages_no_json_marshaller: SmartRollupAddMessages_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupAddMessagesContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupAddMessagesContentsAndResult_no_json_marshaller SmartRollupAddMessagesContentsAndResult

	type json_SmartRollupAddMessagesContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupAddMessagesContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupAddMessagesContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupAddMessagesContentsAndResult_no_json_marshaller: SmartRollupAddMessagesContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupCement) MarshalJSON() ([]byte, error) {
	type SmartRollupCement_no_json_marshaller SmartRollupCement

	type json_SmartRollupCement struct {
		Marker0 any `json:"kind"`
		SmartRollupCement_no_json_marshaller
	}

	tmp := json_SmartRollupCement {
		Marker0: self.OperationKind(),
		SmartRollupCement_no_json_marshaller: SmartRollupCement_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupCementContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupCementContentsAndResult_no_json_marshaller SmartRollupCementContentsAndResult

	type json_SmartRollupCementContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupCementContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupCementContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupCementContentsAndResult_no_json_marshaller: SmartRollupCementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupPublish) MarshalJSON() ([]byte, error) {
	type SmartRollupPublish_no_json_marshaller SmartRollupPublish

	type json_SmartRollupPublish struct {
		Marker0 any `json:"kind"`
		SmartRollupPublish_no_json_marshaller
	}

	tmp := json_SmartRollupPublish {
		Marker0: self.OperationKind(),
		SmartRollupPublish_no_json_marshaller: SmartRollupPublish_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupPublishContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupPublishContentsAndResult_no_json_marshaller SmartRollupPublishContentsAndResult

	type json_SmartRollupPublishContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupPublishContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupPublishContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupPublishContentsAndResult_no_json_marshaller: SmartRollupPublishContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRefute) MarshalJSON() ([]byte, error) {
	type SmartRollupRefute_no_json_marshaller SmartRollupRefute

	type json_SmartRollupRefute struct {
		Marker0 any `json:"kind"`
		SmartRollupRefute_no_json_marshaller
	}

	tmp := json_SmartRollupRefute {
		Marker0: self.OperationKind(),
		SmartRollupRefute_no_json_marshaller: SmartRollupRefute_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRefuteContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupRefuteContentsAndResult_no_json_marshaller SmartRollupRefuteContentsAndResult

	type json_SmartRollupRefuteContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupRefuteContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupRefuteContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupRefuteContentsAndResult_no_json_marshaller: SmartRollupRefuteContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupTimeout) MarshalJSON() ([]byte, error) {
	type SmartRollupTimeout_no_json_marshaller SmartRollupTimeout

	type json_SmartRollupTimeout struct {
		Marker0 any `json:"kind"`
		SmartRollupTimeout_no_json_marshaller
	}

	tmp := json_SmartRollupTimeout {
		Marker0: self.OperationKind(),
		SmartRollupTimeout_no_json_marshaller: SmartRollupTimeout_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupTimeoutContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupTimeoutContentsAndResult_no_json_marshaller SmartRollupTimeoutContentsAndResult

	type json_SmartRollupTimeoutContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupTimeoutContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupTimeoutContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupTimeoutContentsAndResult_no_json_marshaller: SmartRollupTimeoutContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupExecuteOutboxMessage) MarshalJSON() ([]byte, error) {
	type SmartRollupExecuteOutboxMessage_no_json_marshaller SmartRollupExecuteOutboxMessage

	type json_SmartRollupExecuteOutboxMessage struct {
		Marker0 any `json:"kind"`
		SmartRollupExecuteOutboxMessage_no_json_marshaller
	}

	tmp := json_SmartRollupExecuteOutboxMessage {
		Marker0: self.OperationKind(),
		SmartRollupExecuteOutboxMessage_no_json_marshaller: SmartRollupExecuteOutboxMessage_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupExecuteOutboxMessageContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller SmartRollupExecuteOutboxMessageContentsAndResult

	type json_SmartRollupExecuteOutboxMessageContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupExecuteOutboxMessageContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller: SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRecoverBond) MarshalJSON() ([]byte, error) {
	type SmartRollupRecoverBond_no_json_marshaller SmartRollupRecoverBond

	type json_SmartRollupRecoverBond struct {
		Marker0 any `json:"kind"`
		SmartRollupRecoverBond_no_json_marshaller
	}

	tmp := json_SmartRollupRecoverBond {
		Marker0: self.OperationKind(),
		SmartRollupRecoverBond_no_json_marshaller: SmartRollupRecoverBond_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRecoverBondContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupRecoverBondContentsAndResult_no_json_marshaller SmartRollupRecoverBondContentsAndResult

	type json_SmartRollupRecoverBondContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupRecoverBondContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupRecoverBondContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupRecoverBondContentsAndResult_no_json_marshaller: SmartRollupRecoverBondContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DelegationContentsAndResult) MarshalJSON() ([]byte, error) {
	type DelegationContentsAndResult_no_json_marshaller DelegationContentsAndResult

	type json_DelegationContentsAndResult struct {
		Marker0 any `json:"kind"`
		DelegationContentsAndResult_no_json_marshaller
	}

	tmp := json_DelegationContentsAndResult {
		Marker0: self.OperationKind(),
		DelegationContentsAndResult_no_json_marshaller: DelegationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RevealContentsAndResult) MarshalJSON() ([]byte, error) {
	type RevealContentsAndResult_no_json_marshaller RevealContentsAndResult

	type json_RevealContentsAndResult struct {
		Marker0 any `json:"kind"`
		RevealContentsAndResult_no_json_marshaller
	}

	tmp := json_RevealContentsAndResult {
		Marker0: self.OperationKind(),
		RevealContentsAndResult_no_json_marshaller: RevealContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SetDepositsLimitContentsAndResult) MarshalJSON() ([]byte, error) {
	type SetDepositsLimitContentsAndResult_no_json_marshaller SetDepositsLimitContentsAndResult

	type json_SetDepositsLimitContentsAndResult struct {
		Marker0 any `json:"kind"`
		SetDepositsLimitContentsAndResult_no_json_marshaller
	}

	tmp := json_SetDepositsLimitContentsAndResult {
		Marker0: self.OperationKind(),
		SetDepositsLimitContentsAndResult_no_json_marshaller: SetDepositsLimitContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SeedNonceRevelationContentsAndResult) MarshalJSON() ([]byte, error) {
	type SeedNonceRevelationContentsAndResult_no_json_marshaller SeedNonceRevelationContentsAndResult

	type json_SeedNonceRevelationContentsAndResult struct {
		Marker0 any `json:"kind"`
		SeedNonceRevelationContentsAndResult_no_json_marshaller
	}

	tmp := json_SeedNonceRevelationContentsAndResult {
		Marker0: self.OperationKind(),
		SeedNonceRevelationContentsAndResult_no_json_marshaller: SeedNonceRevelationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleEndorsementEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller DoubleEndorsementEvidenceContentsAndResult

	type json_DoubleEndorsementEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleEndorsementEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller: DoubleEndorsementEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *EndorsementContentsAndResult) MarshalJSON() ([]byte, error) {
	type EndorsementContentsAndResult_no_json_marshaller EndorsementContentsAndResult

	type json_EndorsementContentsAndResult struct {
		Marker0 any `json:"kind"`
		EndorsementContentsAndResult_no_json_marshaller
	}

	tmp := json_EndorsementContentsAndResult {
		Marker0: self.OperationKind(),
		EndorsementContentsAndResult_no_json_marshaller: EndorsementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALAttestation) MarshalJSON() ([]byte, error) {
	type DALAttestation_no_json_marshaller DALAttestation

	type json_DALAttestation struct {
		Marker0 any `json:"kind"`
		DALAttestation_no_json_marshaller
	}

	tmp := json_DALAttestation {
		Marker0: self.OperationKind(),
		DALAttestation_no_json_marshaller: DALAttestation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALAttestationContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALAttestationContentsAndResult_no_json_marshaller DALAttestationContentsAndResult

	type json_DALAttestationContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALAttestationContentsAndResult_no_json_marshaller
	}

	tmp := json_DALAttestationContentsAndResult {
		Marker0: self.OperationKind(),
		DALAttestationContentsAndResult_no_json_marshaller: DALAttestationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RegisterGlobalConstantContentsAndResult) MarshalJSON() ([]byte, error) {
	type RegisterGlobalConstantContentsAndResult_no_json_marshaller RegisterGlobalConstantContentsAndResult

	type json_RegisterGlobalConstantContentsAndResult struct {
		Marker0 any `json:"kind"`
		RegisterGlobalConstantContentsAndResult_no_json_marshaller
	}

	tmp := json_RegisterGlobalConstantContentsAndResult {
		Marker0: self.OperationKind(),
		RegisterGlobalConstantContentsAndResult_no_json_marshaller: RegisterGlobalConstantContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateConsensusKeyContentsAndResult) MarshalJSON() ([]byte, error) {
	type UpdateConsensusKeyContentsAndResult_no_json_marshaller UpdateConsensusKeyContentsAndResult

	type json_UpdateConsensusKeyContentsAndResult struct {
		Marker0 any `json:"kind"`
		UpdateConsensusKeyContentsAndResult_no_json_marshaller
	}

	tmp := json_UpdateConsensusKeyContentsAndResult {
		Marker0: self.OperationKind(),
		UpdateConsensusKeyContentsAndResult_no_json_marshaller: UpdateConsensusKeyContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransferTicketContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransferTicketContentsAndResult_no_json_marshaller TransferTicketContentsAndResult

	type json_TransferTicketContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransferTicketContentsAndResult_no_json_marshaller
	}

	tmp := json_TransferTicketContentsAndResult {
		Marker0: self.OperationKind(),
		TransferTicketContentsAndResult_no_json_marshaller: TransferTicketContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorageSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller IncreasePaidStorageSuccessfulManagerResult

	type json_IncreasePaidStorageSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_IncreasePaidStorageSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller: IncreasePaidStorageSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorageContentsAndResult) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorageContentsAndResult_no_json_marshaller IncreasePaidStorageContentsAndResult

	type json_IncreasePaidStorageContentsAndResult struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorageContentsAndResult_no_json_marshaller
	}

	tmp := json_IncreasePaidStorageContentsAndResult {
		Marker0: self.OperationKind(),
		IncreasePaidStorageContentsAndResult_no_json_marshaller: IncreasePaidStorageContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleBakingEvidence) MarshalJSON() ([]byte, error) {
	type DoubleBakingEvidence_no_json_marshaller DoubleBakingEvidence

	type json_DoubleBakingEvidence struct {
		Marker0 any `json:"kind"`
		DoubleBakingEvidence_no_json_marshaller
	}

	tmp := json_DoubleBakingEvidence {
		Marker0: self.OperationKind(),
		DoubleBakingEvidence_no_json_marshaller: DoubleBakingEvidence_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleBakingEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleBakingEvidenceContentsAndResult_no_json_marshaller DoubleBakingEvidenceContentsAndResult

	type json_DoubleBakingEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleBakingEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller: DoubleBakingEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ActivateAccountContentsAndResult) MarshalJSON() ([]byte, error) {
	type ActivateAccountContentsAndResult_no_json_marshaller ActivateAccountContentsAndResult

	type json_ActivateAccountContentsAndResult struct {
		Marker0 any `json:"kind"`
		ActivateAccountContentsAndResult_no_json_marshaller
	}

	tmp := json_ActivateAccountContentsAndResult {
		Marker0: self.OperationKind(),
		ActivateAccountContentsAndResult_no_json_marshaller: ActivateAccountContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoublePreendorsementEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller DoublePreendorsementEvidenceContentsAndResult

	type json_DoublePreendorsementEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoublePreendorsementEvidenceContentsAndResult {
		Marker0: self.OperationKind(),
		DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller: DoublePreendorsementEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreendorsementContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreendorsementContentsAndResult_no_json_marshaller PreendorsementContentsAndResult

	type json_PreendorsementContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreendorsementContentsAndResult_no_json_marshaller
	}

	tmp := json_PreendorsementContentsAndResult {
		Marker0: self.OperationKind(),
		PreendorsementContentsAndResult_no_json_marshaller: PreendorsementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *VDFRevelationContentsAndResult) MarshalJSON() ([]byte, error) {
	type VDFRevelationContentsAndResult_no_json_marshaller VDFRevelationContentsAndResult

	type json_VDFRevelationContentsAndResult struct {
		Marker0 any `json:"kind"`
		VDFRevelationContentsAndResult_no_json_marshaller
	}

	tmp := json_VDFRevelationContentsAndResult {
		Marker0: self.OperationKind(),
		VDFRevelationContentsAndResult_no_json_marshaller: VDFRevelationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DrainDelegateContentsAndResult) MarshalJSON() ([]byte, error) {
	type DrainDelegateContentsAndResult_no_json_marshaller DrainDelegateContentsAndResult

	type json_DrainDelegateContentsAndResult struct {
		Marker0 any `json:"kind"`
		DrainDelegateContentsAndResult_no_json_marshaller
	}

	tmp := json_DrainDelegateContentsAndResult {
		Marker0: self.OperationKind(),
		DrainDelegateContentsAndResult_no_json_marshaller: DrainDelegateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishSlotHeader) MarshalJSON() ([]byte, error) {
	type DALPublishSlotHeader_no_json_marshaller DALPublishSlotHeader

	type json_DALPublishSlotHeader struct {
		Marker0 any `json:"kind"`
		DALPublishSlotHeader_no_json_marshaller
	}

	tmp := json_DALPublishSlotHeader {
		Marker0: self.OperationKind(),
		DALPublishSlotHeader_no_json_marshaller: DALPublishSlotHeader_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishSlotHeaderContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALPublishSlotHeaderContentsAndResult_no_json_marshaller DALPublishSlotHeaderContentsAndResult

	type json_DALPublishSlotHeaderContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller
	}

	tmp := json_DALPublishSlotHeaderContentsAndResult {
		Marker0: self.OperationKind(),
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller: DALPublishSlotHeaderContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type TransactionSuccessfulManagerResult_no_json_marshaller TransactionSuccessfulManagerResult

	type json_TransactionSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		TransactionSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_TransactionSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		TransactionSuccessfulManagerResult_no_json_marshaller: TransactionSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransactionContentsAndResult_no_json_marshaller TransactionContentsAndResult

	type json_TransactionContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransactionContentsAndResult_no_json_marshaller
	}

	tmp := json_TransactionContentsAndResult {
		Marker0: self.OperationKind(),
		TransactionContentsAndResult_no_json_marshaller: TransactionContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionInternalOperationResult) MarshalJSON() ([]byte, error) {
	type TransactionInternalOperationResult_no_json_marshaller TransactionInternalOperationResult

	type json_TransactionInternalOperationResult struct {
		Marker0 any `json:"kind"`
		TransactionInternalOperationResult_no_json_marshaller
	}

	tmp := json_TransactionInternalOperationResult {
		Marker0: self.OperationKind(),
		TransactionInternalOperationResult_no_json_marshaller: TransactionInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupOriginationContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupOriginationContentsAndResult_no_json_marshaller ZkRollupOriginationContentsAndResult

	type json_ZkRollupOriginationContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupOriginationContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupOriginationContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupOriginationContentsAndResult_no_json_marshaller: ZkRollupOriginationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupPublishContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupPublishContentsAndResult_no_json_marshaller ZkRollupPublishContentsAndResult

	type json_ZkRollupPublishContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupPublishContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupPublishContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupPublishContentsAndResult_no_json_marshaller: ZkRollupPublishContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupUpdate) MarshalJSON() ([]byte, error) {
	type ZkRollupUpdate_no_json_marshaller ZkRollupUpdate

	type json_ZkRollupUpdate struct {
		Marker0 any `json:"kind"`
		ZkRollupUpdate_no_json_marshaller
	}

	tmp := json_ZkRollupUpdate {
		Marker0: self.OperationKind(),
		ZkRollupUpdate_no_json_marshaller: ZkRollupUpdate_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupUpdateContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupUpdateContentsAndResult_no_json_marshaller ZkRollupUpdateContentsAndResult

	type json_ZkRollupUpdateContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupUpdateContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupUpdateContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupUpdateContentsAndResult_no_json_marshaller: ZkRollupUpdateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

