package proto_alpha

import (
	"github.com/ecadlabs/gotez/v2/protocol/proto_022_PsRiotum"
)

type SmartRollupOriginate = proto_022_PsRiotum.SmartRollupOriginate
type SmartRollupOriginateContentsAndResult = proto_022_PsRiotum.SmartRollupOriginateContentsAndResult
type SmartRollupAddMessages = proto_022_PsRiotum.SmartRollupAddMessages
type SmartRollupAddMessagesContentsAndResult = proto_022_PsRiotum.SmartRollupAddMessagesContentsAndResult
type SmartRollupCement = proto_022_PsRiotum.SmartRollupCement
type SmartRollupCementContentsAndResult = proto_022_PsRiotum.SmartRollupCementContentsAndResult
type SmartRollupPublish = proto_022_PsRiotum.SmartRollupPublish
type SmartRollupPublishContentsAndResult = proto_022_PsRiotum.SmartRollupPublishContentsAndResult
type SmartRollupRefute = proto_022_PsRiotum.SmartRollupRefute
type SmartRollupRefuteContentsAndResult = proto_022_PsRiotum.SmartRollupRefuteContentsAndResult
type SmartRollupTimeout = proto_022_PsRiotum.SmartRollupTimeout
type SmartRollupTimeoutContentsAndResult = proto_022_PsRiotum.SmartRollupTimeoutContentsAndResult
type SmartRollupExecuteOutboxMessage = proto_022_PsRiotum.SmartRollupExecuteOutboxMessage
type SmartRollupExecuteOutboxMessageContentsAndResult = proto_022_PsRiotum.SmartRollupExecuteOutboxMessageContentsAndResult
type SmartRollupRecoverBond = proto_022_PsRiotum.SmartRollupRecoverBond
type SmartRollupRecoverBondContentsAndResult = proto_022_PsRiotum.SmartRollupRecoverBondContentsAndResult
