package proto_017_PtNairob

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *SmartRollupCementContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupCementContentsAndResult_no_json_marshaller SmartRollupCementContentsAndResult

	type json_SmartRollupCementContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupCementContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupCementContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupCementContentsAndResult_no_json_marshaller: SmartRollupCementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishSlotHeaderContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALPublishSlotHeaderContentsAndResult_no_json_marshaller DALPublishSlotHeaderContentsAndResult

	type json_DALPublishSlotHeaderContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller
	}

	tmp := json_DALPublishSlotHeaderContentsAndResult {
		Marker0: self.OperationKind(),
		DALPublishSlotHeaderContentsAndResult_no_json_marshaller: DALPublishSlotHeaderContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

