package proto_023_PtSEouLo

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *DALEntrapmentEvidence) MarshalJSON() ([]byte, error) {
	type DALEntrapmentEvidence_no_json_marshaller DALEntrapmentEvidence

	type json_DALEntrapmentEvidence struct {
		Marker0 any `json:"kind"`
		DALEntrapmentEvidence_no_json_marshaller
	}

	tmp := json_DALEntrapmentEvidence{
		Marker0:                                  self.OperationKind(),
		DALEntrapmentEvidence_no_json_marshaller: DALEntrapmentEvidence_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *Reveal) MarshalJSON() ([]byte, error) {
	type Reveal_no_json_marshaller Reveal

	type json_Reveal struct {
		Marker0 any `json:"kind"`
		Reveal_no_json_marshaller
	}

	tmp := json_Reveal{
		Marker0:                   self.OperationKind(),
		Reveal_no_json_marshaller: Reveal_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateConsensusKey) MarshalJSON() ([]byte, error) {
	type UpdateConsensusKey_no_json_marshaller UpdateConsensusKey

	type json_UpdateConsensusKey struct {
		Marker0 any `json:"kind"`
		UpdateConsensusKey_no_json_marshaller
	}

	tmp := json_UpdateConsensusKey{
		Marker0:                               self.OperationKind(),
		UpdateConsensusKey_no_json_marshaller: UpdateConsensusKey_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateCompanionKey) MarshalJSON() ([]byte, error) {
	type UpdateCompanionKey_no_json_marshaller UpdateCompanionKey

	type json_UpdateCompanionKey struct {
		Marker0 any `json:"kind"`
		UpdateCompanionKey_no_json_marshaller
	}

	tmp := json_UpdateCompanionKey{
		Marker0:                               self.OperationKind(),
		UpdateCompanionKey_no_json_marshaller: UpdateCompanionKey_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *Attestation) MarshalJSON() ([]byte, error) {
	type Attestation_no_json_marshaller Attestation

	type json_Attestation struct {
		Marker0 any `json:"kind"`
		Attestation_no_json_marshaller
	}

	tmp := json_Attestation{
		Marker0:                        self.OperationKind(),
		Attestation_no_json_marshaller: Attestation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *Preattestation) MarshalJSON() ([]byte, error) {
	type Preattestation_no_json_marshaller Preattestation

	type json_Preattestation struct {
		Marker0 any `json:"kind"`
		Preattestation_no_json_marshaller
	}

	tmp := json_Preattestation{
		Marker0:                           self.OperationKind(),
		Preattestation_no_json_marshaller: Preattestation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationsAggregate) MarshalJSON() ([]byte, error) {
	type AttestationsAggregate_no_json_marshaller AttestationsAggregate

	type json_AttestationsAggregate struct {
		Marker0 any `json:"kind"`
		AttestationsAggregate_no_json_marshaller
	}

	tmp := json_AttestationsAggregate{
		Marker0:                                  self.OperationKind(),
		AttestationsAggregate_no_json_marshaller: AttestationsAggregate_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreattestationsAggregate) MarshalJSON() ([]byte, error) {
	type PreattestationsAggregate_no_json_marshaller PreattestationsAggregate

	type json_PreattestationsAggregate struct {
		Marker0 any `json:"kind"`
		PreattestationsAggregate_no_json_marshaller
	}

	tmp := json_PreattestationsAggregate{
		Marker0: self.OperationKind(),
		PreattestationsAggregate_no_json_marshaller: PreattestationsAggregate_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationWithDAL) MarshalJSON() ([]byte, error) {
	type AttestationWithDAL_no_json_marshaller AttestationWithDAL

	type json_AttestationWithDAL struct {
		Marker0 any `json:"kind"`
		AttestationWithDAL_no_json_marshaller
	}

	tmp := json_AttestationWithDAL{
		Marker0:                               self.OperationKind(),
		AttestationWithDAL_no_json_marshaller: AttestationWithDAL_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BLSModeAttestation) MarshalJSON() ([]byte, error) {
	type BLSModeAttestation_no_json_marshaller BLSModeAttestation

	type json_BLSModeAttestation struct {
		Marker0 any `json:"kind"`
		BLSModeAttestation_no_json_marshaller
	}

	tmp := json_BLSModeAttestation{
		Marker0:                               self.OperationKind(),
		BLSModeAttestation_no_json_marshaller: BLSModeAttestation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *BLSModePreattestation) MarshalJSON() ([]byte, error) {
	type BLSModePreattestation_no_json_marshaller BLSModePreattestation

	type json_BLSModePreattestation struct {
		Marker0 any `json:"kind"`
		BLSModePreattestation_no_json_marshaller
	}

	tmp := json_BLSModePreattestation{
		Marker0:                                  self.OperationKind(),
		BLSModePreattestation_no_json_marshaller: BLSModePreattestation_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleConsensusOperationEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleConsensusOperationEvidenceContentsAndResult_no_json_marshaller DoubleConsensusOperationEvidenceContentsAndResult

	type json_DoubleConsensusOperationEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleConsensusOperationEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleConsensusOperationEvidenceContentsAndResult{
		Marker0: self.OperationKind(),
		DoubleConsensusOperationEvidenceContentsAndResult_no_json_marshaller: DoubleConsensusOperationEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DoubleBakingEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DoubleBakingEvidenceContentsAndResult_no_json_marshaller DoubleBakingEvidenceContentsAndResult

	type json_DoubleBakingEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DoubleBakingEvidenceContentsAndResult{
		Marker0: self.OperationKind(),
		DoubleBakingEvidenceContentsAndResult_no_json_marshaller: DoubleBakingEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationContentsAndResult_no_json_marshaller AttestationContentsAndResult

	type json_AttestationContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationContentsAndResult{
		Marker0: self.OperationKind(),
		AttestationContentsAndResult_no_json_marshaller: AttestationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreattestationContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreattestationContentsAndResult_no_json_marshaller PreattestationContentsAndResult

	type json_PreattestationContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreattestationContentsAndResult_no_json_marshaller
	}

	tmp := json_PreattestationContentsAndResult{
		Marker0: self.OperationKind(),
		PreattestationContentsAndResult_no_json_marshaller: PreattestationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationWithDALContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationWithDALContentsAndResult_no_json_marshaller AttestationWithDALContentsAndResult

	type json_AttestationWithDALContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationWithDALContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationWithDALContentsAndResult{
		Marker0: self.OperationKind(),
		AttestationWithDALContentsAndResult_no_json_marshaller: AttestationWithDALContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALEntrapmentEvidenceContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALEntrapmentEvidenceContentsAndResult_no_json_marshaller DALEntrapmentEvidenceContentsAndResult

	type json_DALEntrapmentEvidenceContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALEntrapmentEvidenceContentsAndResult_no_json_marshaller
	}

	tmp := json_DALEntrapmentEvidenceContentsAndResult{
		Marker0: self.OperationKind(),
		DALEntrapmentEvidenceContentsAndResult_no_json_marshaller: DALEntrapmentEvidenceContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationsAggregateContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationsAggregateContentsAndResult_no_json_marshaller AttestationsAggregateContentsAndResult

	type json_AttestationsAggregateContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationsAggregateContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationsAggregateContentsAndResult{
		Marker0: self.OperationKind(),
		AttestationsAggregateContentsAndResult_no_json_marshaller: AttestationsAggregateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreattestationsAggregateContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreattestationsAggregateContentsAndResult_no_json_marshaller PreattestationsAggregateContentsAndResult

	type json_PreattestationsAggregateContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreattestationsAggregateContentsAndResult_no_json_marshaller
	}

	tmp := json_PreattestationsAggregateContentsAndResult{
		Marker0: self.OperationKind(),
		PreattestationsAggregateContentsAndResult_no_json_marshaller: PreattestationsAggregateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RevealContentsAndResult) MarshalJSON() ([]byte, error) {
	type RevealContentsAndResult_no_json_marshaller RevealContentsAndResult

	type json_RevealContentsAndResult struct {
		Marker0 any `json:"kind"`
		RevealContentsAndResult_no_json_marshaller
	}

	tmp := json_RevealContentsAndResult{
		Marker0: self.OperationKind(),
		RevealContentsAndResult_no_json_marshaller: RevealContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateConsensusKeyContentsAndResult) MarshalJSON() ([]byte, error) {
	type UpdateConsensusKeyContentsAndResult_no_json_marshaller UpdateConsensusKeyContentsAndResult

	type json_UpdateConsensusKeyContentsAndResult struct {
		Marker0 any `json:"kind"`
		UpdateConsensusKeyContentsAndResult_no_json_marshaller
	}

	tmp := json_UpdateConsensusKeyContentsAndResult{
		Marker0: self.OperationKind(),
		UpdateConsensusKeyContentsAndResult_no_json_marshaller: UpdateConsensusKeyContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateConsensusKeySuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type UpdateConsensusKeySuccessfulManagerResult_no_json_marshaller UpdateConsensusKeySuccessfulManagerResult

	type json_UpdateConsensusKeySuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		UpdateConsensusKeySuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_UpdateConsensusKeySuccessfulManagerResult{
		Marker0: self.OperationKind(),
		UpdateConsensusKeySuccessfulManagerResult_no_json_marshaller: UpdateConsensusKeySuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateCompanionKeyContentsAndResult) MarshalJSON() ([]byte, error) {
	type UpdateCompanionKeyContentsAndResult_no_json_marshaller UpdateCompanionKeyContentsAndResult

	type json_UpdateCompanionKeyContentsAndResult struct {
		Marker0 any `json:"kind"`
		UpdateCompanionKeyContentsAndResult_no_json_marshaller
	}

	tmp := json_UpdateCompanionKeyContentsAndResult{
		Marker0: self.OperationKind(),
		UpdateCompanionKeyContentsAndResult_no_json_marshaller: UpdateCompanionKeyContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}
