package proto_013_PtJakart

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *TransactionSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type TransactionSuccessfulManagerResult_no_json_marshaller TransactionSuccessfulManagerResult

	type json_TransactionSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		*TransactionSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_TransactionSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		TransactionSuccessfulManagerResult_no_json_marshaller: (*TransactionSuccessfulManagerResult_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *TransactionInternalOperationResult) MarshalJSON() ([]byte, error) {
	type TransactionInternalOperationResult_no_json_marshaller TransactionInternalOperationResult

	type json_TransactionInternalOperationResult struct {
		Marker0 any `json:"kind"`
		*TransactionInternalOperationResult_no_json_marshaller
	}

	tmp := json_TransactionInternalOperationResult {
		Marker0: self.OperationKind(),
		TransactionInternalOperationResult_no_json_marshaller: (*TransactionInternalOperationResult_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *BalanceUpdateFrozenBonds) MarshalJSON() ([]byte, error) {
	type BalanceUpdateFrozenBonds_no_json_marshaller BalanceUpdateFrozenBonds

	type json_BalanceUpdateFrozenBonds struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		*BalanceUpdateFrozenBonds_no_json_marshaller
	}

	tmp := json_BalanceUpdateFrozenBonds {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateFrozenBonds_no_json_marshaller: (*BalanceUpdateFrozenBonds_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *BalanceUpdateTxRollupRejectionRewards) MarshalJSON() ([]byte, error) {
	type BalanceUpdateTxRollupRejectionRewards_no_json_marshaller BalanceUpdateTxRollupRejectionRewards

	type json_BalanceUpdateTxRollupRejectionRewards struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		*BalanceUpdateTxRollupRejectionRewards_no_json_marshaller
	}

	tmp := json_BalanceUpdateTxRollupRejectionRewards {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateTxRollupRejectionRewards_no_json_marshaller: (*BalanceUpdateTxRollupRejectionRewards_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *BalanceUpdateTxRollupRejectionPunishments) MarshalJSON() ([]byte, error) {
	type BalanceUpdateTxRollupRejectionPunishments_no_json_marshaller BalanceUpdateTxRollupRejectionPunishments

	type json_BalanceUpdateTxRollupRejectionPunishments struct {
		Marker0 any `json:"category"`
		Marker1 any `json:"kind"`
		*BalanceUpdateTxRollupRejectionPunishments_no_json_marshaller
	}

	tmp := json_BalanceUpdateTxRollupRejectionPunishments {
		Marker0: self.BalanceUpdateCategory(),
		Marker1: self.BalanceUpdateKind(),
		BalanceUpdateTxRollupRejectionPunishments_no_json_marshaller: (*BalanceUpdateTxRollupRejectionPunishments_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *TransferTicket) MarshalJSON() ([]byte, error) {
	type TransferTicket_no_json_marshaller TransferTicket

	type json_TransferTicket struct {
		Marker0 any `json:"kind"`
		*TransferTicket_no_json_marshaller
	}

	tmp := json_TransferTicket {
		Marker0: self.OperationKind(),
		TransferTicket_no_json_marshaller: (*TransferTicket_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *DelegationInternalOperationResult) MarshalJSON() ([]byte, error) {
	type DelegationInternalOperationResult_no_json_marshaller DelegationInternalOperationResult

	type json_DelegationInternalOperationResult struct {
		Marker0 any `json:"kind"`
		*DelegationInternalOperationResult_no_json_marshaller
	}

	tmp := json_DelegationInternalOperationResult {
		Marker0: self.OperationKind(),
		DelegationInternalOperationResult_no_json_marshaller: (*DelegationInternalOperationResult_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *OriginationSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type OriginationSuccessfulManagerResult_no_json_marshaller OriginationSuccessfulManagerResult

	type json_OriginationSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		*OriginationSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_OriginationSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		OriginationSuccessfulManagerResult_no_json_marshaller: (*OriginationSuccessfulManagerResult_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

func (self *OriginationInternalOperationResult) MarshalJSON() ([]byte, error) {
	type OriginationInternalOperationResult_no_json_marshaller OriginationInternalOperationResult

	type json_OriginationInternalOperationResult struct {
		Marker0 any `json:"kind"`
		*OriginationInternalOperationResult_no_json_marshaller
	}

	tmp := json_OriginationInternalOperationResult {
		Marker0: self.OperationKind(),
		OriginationInternalOperationResult_no_json_marshaller: (*OriginationInternalOperationResult_no_json_marshaller)(self),
	}

	return json.Marshal(&tmp)
}

