package monitor

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	"github.com/ecadlabs/gotez/v2/clientv2/internal/transport"
)

// Code generated by generate.go DO NOT EDIT.


var path_Heads = template.Must(template.New("path").Parse("/monitor/heads/{{.Chain}}"))

func Heads(ctx context.Context, cl *client.Client, r *HeadsRequest) (<-chan *Head, <-chan error, error) {
	var path strings.Builder
	if err := path_Heads.Execute(&path, r); err != nil {
		return nil, nil, err
	}
	params := map[string]any{
		"next_protocol": r.NextProtocol,
		"protocol": r.Protocol,
	}
	return transport.Stream[Head](ctx, (*transport.Transport)(cl), path.String(), params)
}

