package proto_024_PtTALLiN

import "encoding/json"

// Code generated by genmarshaller.go DO NOT EDIT.

func (self *PreattestationContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreattestationContentsAndResult_no_json_marshaller PreattestationContentsAndResult

	type json_PreattestationContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreattestationContentsAndResult_no_json_marshaller
	}

	tmp := json_PreattestationContentsAndResult {
		Marker0: self.OperationKind(),
		PreattestationContentsAndResult_no_json_marshaller: PreattestationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationContentsAndResult_no_json_marshaller AttestationContentsAndResult

	type json_AttestationContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationContentsAndResult {
		Marker0: self.OperationKind(),
		AttestationContentsAndResult_no_json_marshaller: AttestationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationWithDALContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationWithDALContentsAndResult_no_json_marshaller AttestationWithDALContentsAndResult

	type json_AttestationWithDALContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationWithDALContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationWithDALContentsAndResult {
		Marker0: self.OperationKind(),
		AttestationWithDALContentsAndResult_no_json_marshaller: AttestationWithDALContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *AttestationsAggregateContentsAndResult) MarshalJSON() ([]byte, error) {
	type AttestationsAggregateContentsAndResult_no_json_marshaller AttestationsAggregateContentsAndResult

	type json_AttestationsAggregateContentsAndResult struct {
		Marker0 any `json:"kind"`
		AttestationsAggregateContentsAndResult_no_json_marshaller
	}

	tmp := json_AttestationsAggregateContentsAndResult {
		Marker0: self.OperationKind(),
		AttestationsAggregateContentsAndResult_no_json_marshaller: AttestationsAggregateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *PreattestationsAggregateContentsAndResult) MarshalJSON() ([]byte, error) {
	type PreattestationsAggregateContentsAndResult_no_json_marshaller PreattestationsAggregateContentsAndResult

	type json_PreattestationsAggregateContentsAndResult struct {
		Marker0 any `json:"kind"`
		PreattestationsAggregateContentsAndResult_no_json_marshaller
	}

	tmp := json_PreattestationsAggregateContentsAndResult {
		Marker0: self.OperationKind(),
		PreattestationsAggregateContentsAndResult_no_json_marshaller: PreattestationsAggregateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RevealContentsAndResult) MarshalJSON() ([]byte, error) {
	type RevealContentsAndResult_no_json_marshaller RevealContentsAndResult

	type json_RevealContentsAndResult struct {
		Marker0 any `json:"kind"`
		RevealContentsAndResult_no_json_marshaller
	}

	tmp := json_RevealContentsAndResult {
		Marker0: self.OperationKind(),
		RevealContentsAndResult_no_json_marshaller: RevealContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *OriginationContentsAndResult) MarshalJSON() ([]byte, error) {
	type OriginationContentsAndResult_no_json_marshaller OriginationContentsAndResult

	type json_OriginationContentsAndResult struct {
		Marker0 any `json:"kind"`
		OriginationContentsAndResult_no_json_marshaller
	}

	tmp := json_OriginationContentsAndResult {
		Marker0: self.OperationKind(),
		OriginationContentsAndResult_no_json_marshaller: OriginationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DelegationContentsAndResult) MarshalJSON() ([]byte, error) {
	type DelegationContentsAndResult_no_json_marshaller DelegationContentsAndResult

	type json_DelegationContentsAndResult struct {
		Marker0 any `json:"kind"`
		DelegationContentsAndResult_no_json_marshaller
	}

	tmp := json_DelegationContentsAndResult {
		Marker0: self.OperationKind(),
		DelegationContentsAndResult_no_json_marshaller: DelegationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *RegisterGlobalConstantContentsAndResult) MarshalJSON() ([]byte, error) {
	type RegisterGlobalConstantContentsAndResult_no_json_marshaller RegisterGlobalConstantContentsAndResult

	type json_RegisterGlobalConstantContentsAndResult struct {
		Marker0 any `json:"kind"`
		RegisterGlobalConstantContentsAndResult_no_json_marshaller
	}

	tmp := json_RegisterGlobalConstantContentsAndResult {
		Marker0: self.OperationKind(),
		RegisterGlobalConstantContentsAndResult_no_json_marshaller: RegisterGlobalConstantContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SetDepositsLimitContentsAndResult) MarshalJSON() ([]byte, error) {
	type SetDepositsLimitContentsAndResult_no_json_marshaller SetDepositsLimitContentsAndResult

	type json_SetDepositsLimitContentsAndResult struct {
		Marker0 any `json:"kind"`
		SetDepositsLimitContentsAndResult_no_json_marshaller
	}

	tmp := json_SetDepositsLimitContentsAndResult {
		Marker0: self.OperationKind(),
		SetDepositsLimitContentsAndResult_no_json_marshaller: SetDepositsLimitContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *IncreasePaidStorageContentsAndResult) MarshalJSON() ([]byte, error) {
	type IncreasePaidStorageContentsAndResult_no_json_marshaller IncreasePaidStorageContentsAndResult

	type json_IncreasePaidStorageContentsAndResult struct {
		Marker0 any `json:"kind"`
		IncreasePaidStorageContentsAndResult_no_json_marshaller
	}

	tmp := json_IncreasePaidStorageContentsAndResult {
		Marker0: self.OperationKind(),
		IncreasePaidStorageContentsAndResult_no_json_marshaller: IncreasePaidStorageContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateConsensusKeyContentsAndResult) MarshalJSON() ([]byte, error) {
	type UpdateConsensusKeyContentsAndResult_no_json_marshaller UpdateConsensusKeyContentsAndResult

	type json_UpdateConsensusKeyContentsAndResult struct {
		Marker0 any `json:"kind"`
		UpdateConsensusKeyContentsAndResult_no_json_marshaller
	}

	tmp := json_UpdateConsensusKeyContentsAndResult {
		Marker0: self.OperationKind(),
		UpdateConsensusKeyContentsAndResult_no_json_marshaller: UpdateConsensusKeyContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *UpdateCompanionKeyContentsAndResult) MarshalJSON() ([]byte, error) {
	type UpdateCompanionKeyContentsAndResult_no_json_marshaller UpdateCompanionKeyContentsAndResult

	type json_UpdateCompanionKeyContentsAndResult struct {
		Marker0 any `json:"kind"`
		UpdateCompanionKeyContentsAndResult_no_json_marshaller
	}

	tmp := json_UpdateCompanionKeyContentsAndResult {
		Marker0: self.OperationKind(),
		UpdateCompanionKeyContentsAndResult_no_json_marshaller: UpdateCompanionKeyContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransferTicketContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransferTicketContentsAndResult_no_json_marshaller TransferTicketContentsAndResult

	type json_TransferTicketContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransferTicketContentsAndResult_no_json_marshaller
	}

	tmp := json_TransferTicketContentsAndResult {
		Marker0: self.OperationKind(),
		TransferTicketContentsAndResult_no_json_marshaller: TransferTicketContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *DALPublishCommitmentContentsAndResult) MarshalJSON() ([]byte, error) {
	type DALPublishCommitmentContentsAndResult_no_json_marshaller DALPublishCommitmentContentsAndResult

	type json_DALPublishCommitmentContentsAndResult struct {
		Marker0 any `json:"kind"`
		DALPublishCommitmentContentsAndResult_no_json_marshaller
	}

	tmp := json_DALPublishCommitmentContentsAndResult {
		Marker0: self.OperationKind(),
		DALPublishCommitmentContentsAndResult_no_json_marshaller: DALPublishCommitmentContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupOriginateContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupOriginateContentsAndResult_no_json_marshaller SmartRollupOriginateContentsAndResult

	type json_SmartRollupOriginateContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupOriginateContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupOriginateContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupOriginateContentsAndResult_no_json_marshaller: SmartRollupOriginateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupAddMessagesContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupAddMessagesContentsAndResult_no_json_marshaller SmartRollupAddMessagesContentsAndResult

	type json_SmartRollupAddMessagesContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupAddMessagesContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupAddMessagesContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupAddMessagesContentsAndResult_no_json_marshaller: SmartRollupAddMessagesContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupCementContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupCementContentsAndResult_no_json_marshaller SmartRollupCementContentsAndResult

	type json_SmartRollupCementContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupCementContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupCementContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupCementContentsAndResult_no_json_marshaller: SmartRollupCementContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupPublishContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupPublishContentsAndResult_no_json_marshaller SmartRollupPublishContentsAndResult

	type json_SmartRollupPublishContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupPublishContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupPublishContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupPublishContentsAndResult_no_json_marshaller: SmartRollupPublishContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRefuteContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupRefuteContentsAndResult_no_json_marshaller SmartRollupRefuteContentsAndResult

	type json_SmartRollupRefuteContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupRefuteContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupRefuteContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupRefuteContentsAndResult_no_json_marshaller: SmartRollupRefuteContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupTimeoutContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupTimeoutContentsAndResult_no_json_marshaller SmartRollupTimeoutContentsAndResult

	type json_SmartRollupTimeoutContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupTimeoutContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupTimeoutContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupTimeoutContentsAndResult_no_json_marshaller: SmartRollupTimeoutContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupExecuteOutboxMessageContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller SmartRollupExecuteOutboxMessageContentsAndResult

	type json_SmartRollupExecuteOutboxMessageContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupExecuteOutboxMessageContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller: SmartRollupExecuteOutboxMessageContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *SmartRollupRecoverBondContentsAndResult) MarshalJSON() ([]byte, error) {
	type SmartRollupRecoverBondContentsAndResult_no_json_marshaller SmartRollupRecoverBondContentsAndResult

	type json_SmartRollupRecoverBondContentsAndResult struct {
		Marker0 any `json:"kind"`
		SmartRollupRecoverBondContentsAndResult_no_json_marshaller
	}

	tmp := json_SmartRollupRecoverBondContentsAndResult {
		Marker0: self.OperationKind(),
		SmartRollupRecoverBondContentsAndResult_no_json_marshaller: SmartRollupRecoverBondContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionContentsAndResult) MarshalJSON() ([]byte, error) {
	type TransactionContentsAndResult_no_json_marshaller TransactionContentsAndResult

	type json_TransactionContentsAndResult struct {
		Marker0 any `json:"kind"`
		TransactionContentsAndResult_no_json_marshaller
	}

	tmp := json_TransactionContentsAndResult {
		Marker0: self.OperationKind(),
		TransactionContentsAndResult_no_json_marshaller: TransactionContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionInternalOperationResult) MarshalJSON() ([]byte, error) {
	type TransactionInternalOperationResult_no_json_marshaller TransactionInternalOperationResult

	type json_TransactionInternalOperationResult struct {
		Marker0 any `json:"kind"`
		TransactionInternalOperationResult_no_json_marshaller
	}

	tmp := json_TransactionInternalOperationResult {
		Marker0: self.OperationKind(),
		TransactionInternalOperationResult_no_json_marshaller: TransactionInternalOperationResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *TransactionSuccessfulManagerResult) MarshalJSON() ([]byte, error) {
	type TransactionSuccessfulManagerResult_no_json_marshaller TransactionSuccessfulManagerResult

	type json_TransactionSuccessfulManagerResult struct {
		Marker0 any `json:"kind"`
		TransactionSuccessfulManagerResult_no_json_marshaller
	}

	tmp := json_TransactionSuccessfulManagerResult {
		Marker0: self.OperationKind(),
		TransactionSuccessfulManagerResult_no_json_marshaller: TransactionSuccessfulManagerResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupOriginationContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupOriginationContentsAndResult_no_json_marshaller ZkRollupOriginationContentsAndResult

	type json_ZkRollupOriginationContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupOriginationContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupOriginationContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupOriginationContentsAndResult_no_json_marshaller: ZkRollupOriginationContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupPublishContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupPublishContentsAndResult_no_json_marshaller ZkRollupPublishContentsAndResult

	type json_ZkRollupPublishContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupPublishContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupPublishContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupPublishContentsAndResult_no_json_marshaller: ZkRollupPublishContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

func (self *ZkRollupUpdateContentsAndResult) MarshalJSON() ([]byte, error) {
	type ZkRollupUpdateContentsAndResult_no_json_marshaller ZkRollupUpdateContentsAndResult

	type json_ZkRollupUpdateContentsAndResult struct {
		Marker0 any `json:"kind"`
		ZkRollupUpdateContentsAndResult_no_json_marshaller
	}

	tmp := json_ZkRollupUpdateContentsAndResult {
		Marker0: self.OperationKind(),
		ZkRollupUpdateContentsAndResult_no_json_marshaller: ZkRollupUpdateContentsAndResult_no_json_marshaller(*self),
	}

	return json.Marshal(tmp)
}

