package block

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	"github.com/ecadlabs/gotez/v2"
	"github.com/ecadlabs/gotez/v2/protocol"
	"github.com/ecadlabs/gotez/v2/protocol/core"
	"github.com/ecadlabs/gotez/v2/protocol/latest"
)

// Code generated by generate.go DO NOT EDIT.


var path_Hash = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/hash"))

func Hash(ctx context.Context, cl *client.Client, r *SimpleRequest) (*gotez.BlockHash, error) {
	var path strings.Builder
	if err := path_Hash.Execute(&path, r); err != nil {
		return nil, err
	}
	response := new(gotez.BlockHash)
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_Protocols = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/protocols"))

func Protocols(ctx context.Context, cl *client.Client, r *SimpleRequest) (*core.BlockProtocols, error) {
	var path strings.Builder
	if err := path_Protocols.Execute(&path, r); err != nil {
		return nil, err
	}
	response := new(core.BlockProtocols)
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_ShellHeader = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/header/shell"))

func ShellHeader(ctx context.Context, cl *client.Client, r *SimpleRequest) (*core.ShellHeader, error) {
	var path strings.Builder
	if err := path_ShellHeader.Execute(&path, r); err != nil {
		return nil, err
	}
	response := new(core.ShellHeader)
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_Header = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/header"))

func Header(ctx context.Context, cl *client.Client, r *BlockRequest) (protocol.BlockHeaderInfo, error) {
	var path strings.Builder
	if err := path_Header.Execute(&path, r); err != nil {
		return nil, err
	}
	params := map[string]any{
		"metadata": r.Metadata,
	}
	response, err := protocol.NewBlockHeaderInfo(r.Protocol)
	if err != nil {
		return nil, err
	}
	if err := cl.Request(ctx, "GET", path.String(), params, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_Block = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}"))

func Block(ctx context.Context, cl *client.Client, r *BlockRequest) (protocol.BlockInfo, error) {
	var path strings.Builder
	if err := path_Block.Execute(&path, r); err != nil {
		return nil, err
	}
	params := map[string]any{
		"metadata": r.Metadata,
	}
	response, err := protocol.NewBlockInfo(r.Protocol)
	if err != nil {
		return nil, err
	}
	if err := cl.Request(ctx, "GET", path.String(), params, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_ContractBalance = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/balance"))

func ContractBalance(ctx context.Context, cl *client.Client, r *ContractRequest) (gotez.BigUint, error) {
	var path strings.Builder
	if err := path_ContractBalance.Execute(&path, r); err != nil {
		return nil, err
	}
	var response gotez.BigUint
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_ContractBalanceAndFrozenBonds = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/balance_and_frozen_bonds"))

func ContractBalanceAndFrozenBonds(ctx context.Context, cl *client.Client, r *ContractRequest) (gotez.BigUint, error) {
	var path strings.Builder
	if err := path_ContractBalanceAndFrozenBonds.Execute(&path, r); err != nil {
		return nil, err
	}
	var response gotez.BigUint
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_ContractCounter = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/context/contracts/{{.ID}}/counter"))

func ContractCounter(ctx context.Context, cl *client.Client, r *ContractRequest) (gotez.BigUint, error) {
	var path strings.Builder
	if err := path_ContractCounter.Execute(&path, r); err != nil {
		return nil, err
	}
	var response gotez.BigUint
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_RunOperation = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/helpers/scripts/run_operation"))

func RunOperation(ctx context.Context, cl *client.Client, r *RunOperationRequest) (*latest.OperationWithOptionalMetadata, error) {
	var path strings.Builder
	if err := path_RunOperation.Execute(&path, r); err != nil {
		return nil, err
	}
	payload := r.Payload
	response := new(latest.OperationWithOptionalMetadata)
	if err := cl.Request(ctx, "POST", path.String(), nil, payload, response); err != nil {
		return nil, err
	}
	return response, nil
}


var path_Constants = template.Must(template.New("path").Parse("/chains/{{.Chain}}/blocks/{{.Block}}/context/constants"))

func Constants(ctx context.Context, cl *client.Client, r *ContextRequest) (core.Constants, error) {
	var path strings.Builder
	if err := path_Constants.Execute(&path, r); err != nil {
		return nil, err
	}
	response, err := protocol.NewConstants(r.Protocol)
	if err != nil {
		return nil, err
	}
	if err := cl.Request(ctx, "GET", path.String(), nil, nil, response); err != nil {
		return nil, err
	}
	return response, nil
}

