package generate

import (
	"os"
	"strings"
	"text/template"
)

const (
	ModeVar       = "var"
	ModeConstruct = "construct"
	ModeAllocate  = "alloc"
)

type QueryParam struct {
	Field string
	Param string
}

type TypeDef struct {
	Func          string
	RequestType   string
	Path          string
	QueryParams   map[string]string
	Method        string
	ResponseType  string
	AllocMode     string
	PtrResult     bool
	ConstructExpr func(proto string) string
	Stream        bool
}

func (t *TypeDef) Construct(proto string) string {
	return t.ConstructExpr(proto)
}

type TemplateData struct {
	Package string
	Import  []string
	Types   []*TypeDef
}

const tplSrc = `package {{.Package}}

import (
	"context"
	"strings"
	"text/template"
	client "github.com/ecadlabs/gotez/v2/clientv2"
	{{- range .Import}}
	"{{.}}"
	{{- end}}
)

// Code generated by generate.go DO NOT EDIT.
{{range .Types}}
{{$template := print "path_" (replace .Func "." "_")}}
var {{$template}} = template.Must(template.New("path").Parse("{{.Path}}"))

func {{.Func}}(ctx context.Context, cl *client.Client, r *{{.RequestType}}) ({{if .Stream}}<-chan *{{.ResponseType}}, <-chan error{{else}}{{if .PtrResult}}*{{end}}{{.ResponseType}}{{end}}, error) {
	var path strings.Builder
	if err := {{$template}}.Execute(&path, r); err != nil {
		return {{if .Stream}}nil, {{end}}nil, err
	}
	{{with .QueryParams -}}
	params := map[string]any{
		{{- range $p, $f := .}}
		"{{$p}}": r.{{$f}},{{end}}
	}
	{{end -}}
	{{if .Stream -}}
	return client.Stream[{{.ResponseType}}](ctx, cl, path.String(), {{if .QueryParams}}params{{else}}nil{{end}})
	{{- else -}}
	{{if eq .Method "POST" -}}
	payload := r.Payload
	{{end -}}
	{{if eq .AllocMode "var" -}}
	var response {{.ResponseType}}
	{{else if eq .AllocMode "alloc" -}}
	response := new({{.ResponseType}})
	{{else -}}
	response, err := {{.Construct "r.Protocol"}}
	if err != nil {
		return nil, err
	}
	{{end -}}
	if err := cl.Request(ctx, "{{.Method}}", path.String(), {{if .QueryParams}}params{{else}}nil{{end}}, {{if eq .Method "POST" -}}payload{{else}}nil{{end}}, {{if eq .AllocMode "var"}}&{{end}}response); err != nil {
		return nil, err
	}
	return response, nil
	{{- end}}
}
{{end}}
`

var tpl = template.Must(template.New("formatter").Funcs(template.FuncMap{
	"replace": func(s, old, new string) string { return strings.Replace(s, old, new, -1) },
}).Parse(tplSrc))

const outName = "request_gen.go"

func Execute(data *TemplateData) error {
	fd, err := os.Create(outName)
	if err != nil {
		return err
	}
	defer fd.Close()
	return tpl.Execute(fd, data)
}
