on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.19.0"
      - uses: actions/checkout@v3
      - run: go test ./...
