name: Test

on:
  push:
    branches: [v2]
  pull_request:
    branches: [v2]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go vet ./...

      - run: go test -race -count=1 ./...
